In [2]:
import json
import pandas as pd

In [4]:
f = open('feature_names.json')
feature_names = json.load(f)

In [7]:
prostate_populations = [15, 16]

In [13]:
import json
import pandas as pd

# Load valid feature names from features.json
with open('feature_names.json', 'r') as f:
    valid_feature_names = json.load(f)

# Assuming you have already loaded multiclass_phenotype and pop_count_data DataFrames

multiclass_path = f"/wynton/protected/home/fhuanglab/ardademirci/Data_Specific_Epithelial/wynton_code/phenotype_multiclass_label/data_15_phenotype_multiclass.txt"
count_path = f"/wynton/protected/home/fhuanglab/ardademirci/Data_Specific_Epithelial/wynton_code/nn_files/count_data/data_15_count.txt"
multiclass_phenotype = pd.read_csv(multiclass_path, sep='\t')
pop_count_data = pd.read_csv(count_path, sep='\t')

In [26]:
len(feature_names)

23196

In [25]:
multiclass_phenotype

                                              barcode phenotype
0      TAAGCAGTGGTA_2_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1     Tumor
1      AAGCAGTGGTAT_2_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1     Tumor
2      TCCAAGCAGTGG_2_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1     Tumor
3      TGTAAGCAGTGG_2_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1     Tumor
4      TTAAGCAGTGGT_2_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1     Tumor
...                                               ...       ...
11055                              TGGCAGCCTCCA_2_2_2     Tumor
11056                              CCCTCAAATGGG_2_2_2     Tumor
11057                              CAAGTTTGTAGC_2_2_2     Tumor
11058                              CCCAAGACTTGT_2_2_2     Tumor
11059                              CGTAGGGTCGCA_2_2_2     Tumor

[11060 rows x 2 columns]

In [24]:
pop_count_data

,TAAGCAGTGGTA_2_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1,AAGCAGTGGTAT_2_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1,TCCAAGCAGTGG_2_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1,TGTAAGCAGTGG_2_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1,TTAAGCAGTGGT_2_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1,TCGGGGGGGGGG_2_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1,TCCTAAGCAGTG_2_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1,TCGCTAAGCAGT_2_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1,TTGCGCGACACC_2_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1,TGATCCCCGCTA_2_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1,...,TCGATCCACATG_2_2_2,TCCTCCCGCATC_2_2_2,CTCCGATCTGGG_2_2_2,CGATCGTACGCT_2_2_2,CATCGATTGGCT_2_2_2,TGGCAGCCTCCA_2_2_2,CCCTCAAATGGG_2_2_2,CAAGTTTGTAGC_2_2_2,CCCAAGACTTGT_2_2_2,CGTAGGGTCGCA_2_2_2
0,1.035433,1.109966,1.70197,0.0,0.0,1.481956,0.0,1.805656,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.000000,0.000000,0.00000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.000000,1.421489,0.00000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.000000,1.483398,0.00000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.000000,0.000000,0.00000,0.0,0.0,1.773179,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26554,0.000000,0.000000,0.00000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26555,0.000000,0.000000,0.00000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26556,0.000000,0.000000,0.00000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26557,0.000000,0.000000,0.00000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26558,0.000000,0.000000,0.00000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
for population in prostate_populations:
    print(f"Population {population} started scaling.")
    multiclass_path = f"/wynton/protected/home/fhuanglab/ardademirci/Data_Specific_Epithelial/wynton_code/phenotype_multiclass_label/data_{population}_phenotype_multiclass.txt"
    count_path = f"/wynton/protected/home/fhuanglab/ardademirci/Data_Specific_Epithelial/wynton_code/nn_files/count_data/data_{population}_count.txt"
    multiclass_phenotype = pd.read_csv(multiclass_path, sep='\t')
    pop_count_data = pd.read_csv(count_path, sep='\t')
    pop_count_data = pop_count_data.T

    pop_count_data['vector'] = pop_count_data.apply(lambda row: row.values, axis=1)
    pop_count_data = pop_count_data[['vector']]
    # pop_count_data['Barcode'] = pop_count_data.index
    pop_count_data['barcode'] = pop_count_data.index
    pop_count_data = pop_count_data.reset_index(drop=True)

    df1 = multiclass_phenotype 
    df2 = pop_count_data

    merged_multiclass = df1.merge(df2, on='barcode', how='inner')
    # merged_multiclass = merged_multiclass.rename(columns={'Barcode': 'barcode', 'Phenotype': 'phenotype'})

    # Extract the 'vector' column as a separate DataFrame
    vectors_df = pd.DataFrame(merged_multiclass['vector'].tolist())